[2024-06-19T18:29:56.629+0000] {processor.py:161} INFO - Started process (PID=13) to work on /opt/airflow/dags/fill_data.py
[2024-06-19T18:29:56.630+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/fill_data.py for tasks to queue
[2024-06-19T18:29:56.631+0000] {logging_mixin.py:188} INFO - [2024-06-19T18:29:56.631+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/fill_data.py
[2024-06-19T18:29:56.634+0000] {logging_mixin.py:188} INFO - [2024-06-19T18:29:56.633+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/fill_data.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/fill_data.py", line 36
    del equipos_actuales(random_equipo)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: cannot delete function call
[2024-06-19T18:29:56.634+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/fill_data.py
[2024-06-19T18:29:56.644+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/fill_data.py took 0.018 seconds
[2024-06-19T18:30:27.747+0000] {processor.py:161} INFO - Started process (PID=37) to work on /opt/airflow/dags/fill_data.py
[2024-06-19T18:30:27.748+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/fill_data.py for tasks to queue
[2024-06-19T18:30:27.749+0000] {logging_mixin.py:188} INFO - [2024-06-19T18:30:27.748+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/fill_data.py
[2024-06-19T18:30:27.751+0000] {logging_mixin.py:188} INFO - [2024-06-19T18:30:27.751+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/fill_data.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/fill_data.py", line 36
    del equipos_actuales(random_equipo)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: cannot delete function call
[2024-06-19T18:30:27.751+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/fill_data.py
[2024-06-19T18:30:27.759+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/fill_data.py took 0.014 seconds
[2024-06-19T18:30:57.901+0000] {processor.py:161} INFO - Started process (PID=44) to work on /opt/airflow/dags/fill_data.py
[2024-06-19T18:30:57.902+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/fill_data.py for tasks to queue
[2024-06-19T18:30:57.905+0000] {logging_mixin.py:188} INFO - [2024-06-19T18:30:57.904+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/fill_data.py
[2024-06-19T18:30:57.911+0000] {logging_mixin.py:188} INFO - [2024-06-19T18:30:57.910+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/fill_data.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/fill_data.py", line 36
    del equipos_actuales(random_equipo)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: cannot delete function call
[2024-06-19T18:30:57.912+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/fill_data.py
[2024-06-19T18:30:57.926+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/fill_data.py took 0.031 seconds
[2024-06-19T18:31:28.929+0000] {processor.py:161} INFO - Started process (PID=52) to work on /opt/airflow/dags/fill_data.py
[2024-06-19T18:31:28.929+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/fill_data.py for tasks to queue
[2024-06-19T18:31:28.931+0000] {logging_mixin.py:188} INFO - [2024-06-19T18:31:28.931+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/fill_data.py
[2024-06-19T18:31:28.935+0000] {logging_mixin.py:188} INFO - [2024-06-19T18:31:28.935+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/fill_data.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/fill_data.py", line 36
    del equipos_actuales(random_equipo)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: cannot delete function call
[2024-06-19T18:31:28.936+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/fill_data.py
[2024-06-19T18:31:28.943+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/fill_data.py took 0.019 seconds
[2024-06-19T18:31:59.758+0000] {processor.py:161} INFO - Started process (PID=59) to work on /opt/airflow/dags/fill_data.py
[2024-06-19T18:31:59.759+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/fill_data.py for tasks to queue
[2024-06-19T18:31:59.762+0000] {logging_mixin.py:188} INFO - [2024-06-19T18:31:59.761+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/fill_data.py
[2024-06-19T18:31:59.768+0000] {logging_mixin.py:188} INFO - [2024-06-19T18:31:59.767+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/fill_data.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/fill_data.py", line 36
    del equipos_actuales(random_equipo)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: cannot delete function call
[2024-06-19T18:31:59.768+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/fill_data.py
[2024-06-19T18:31:59.783+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/fill_data.py took 0.032 seconds
[2024-06-19T18:32:30.695+0000] {processor.py:161} INFO - Started process (PID=66) to work on /opt/airflow/dags/fill_data.py
[2024-06-19T18:32:30.696+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/fill_data.py for tasks to queue
[2024-06-19T18:32:30.698+0000] {logging_mixin.py:188} INFO - [2024-06-19T18:32:30.698+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/fill_data.py
[2024-06-19T18:32:30.705+0000] {logging_mixin.py:188} INFO - [2024-06-19T18:32:30.704+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/fill_data.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/fill_data.py", line 36
    del equipos_actuales(random_equipo)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: cannot delete function call
[2024-06-19T18:32:30.706+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/fill_data.py
[2024-06-19T18:32:30.721+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/fill_data.py took 0.032 seconds
[2024-06-19T18:33:01.311+0000] {processor.py:161} INFO - Started process (PID=73) to work on /opt/airflow/dags/fill_data.py
[2024-06-19T18:33:01.312+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/fill_data.py for tasks to queue
[2024-06-19T18:33:01.317+0000] {logging_mixin.py:188} INFO - [2024-06-19T18:33:01.316+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/fill_data.py
[2024-06-19T18:33:01.322+0000] {logging_mixin.py:188} INFO - [2024-06-19T18:33:01.321+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/fill_data.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/fill_data.py", line 36
    del equipos_actuales(random_equipo)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: cannot delete function call
[2024-06-19T18:33:01.323+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/fill_data.py
[2024-06-19T18:33:01.337+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/fill_data.py took 0.033 seconds
[2024-06-19T18:33:31.881+0000] {processor.py:161} INFO - Started process (PID=80) to work on /opt/airflow/dags/fill_data.py
[2024-06-19T18:33:31.882+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/fill_data.py for tasks to queue
[2024-06-19T18:33:31.884+0000] {logging_mixin.py:188} INFO - [2024-06-19T18:33:31.884+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/fill_data.py
[2024-06-19T18:33:31.891+0000] {logging_mixin.py:188} INFO - [2024-06-19T18:33:31.890+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/fill_data.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/fill_data.py", line 36
    del equipos_actuales(random_equipo)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: cannot delete function call
[2024-06-19T18:33:31.892+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/fill_data.py
[2024-06-19T18:33:31.906+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/fill_data.py took 0.033 seconds
[2024-06-19T18:34:02.382+0000] {processor.py:161} INFO - Started process (PID=87) to work on /opt/airflow/dags/fill_data.py
[2024-06-19T18:34:02.383+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/fill_data.py for tasks to queue
[2024-06-19T18:34:02.385+0000] {logging_mixin.py:188} INFO - [2024-06-19T18:34:02.385+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/fill_data.py
[2024-06-19T18:34:02.391+0000] {logging_mixin.py:188} INFO - [2024-06-19T18:34:02.390+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/fill_data.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/fill_data.py", line 36
    del equipos_actuales(random_equipo)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: cannot delete function call
[2024-06-19T18:34:02.392+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/fill_data.py
[2024-06-19T18:34:02.406+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/fill_data.py took 0.031 seconds
[2024-06-19T18:34:33.759+0000] {processor.py:161} INFO - Started process (PID=94) to work on /opt/airflow/dags/fill_data.py
[2024-06-19T18:34:33.760+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/fill_data.py for tasks to queue
[2024-06-19T18:34:33.761+0000] {logging_mixin.py:188} INFO - [2024-06-19T18:34:33.761+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/fill_data.py
[2024-06-19T18:34:33.766+0000] {logging_mixin.py:188} INFO - [2024-06-19T18:34:33.765+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/fill_data.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/fill_data.py", line 36
    del equipos_actuales(random_equipo)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: cannot delete function call
[2024-06-19T18:34:33.766+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/fill_data.py
[2024-06-19T18:34:33.777+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/fill_data.py took 0.024 seconds
[2024-06-19T18:35:07.318+0000] {processor.py:161} INFO - Started process (PID=101) to work on /opt/airflow/dags/fill_data.py
[2024-06-19T18:35:07.318+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/fill_data.py for tasks to queue
[2024-06-19T18:35:07.320+0000] {logging_mixin.py:188} INFO - [2024-06-19T18:35:07.319+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/fill_data.py
[2024-06-19T18:35:07.323+0000] {logging_mixin.py:188} INFO - [2024-06-19T18:35:07.323+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/fill_data.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/fill_data.py", line 36
    del equipos_actuales(random_equipo)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: cannot delete function call
[2024-06-19T18:35:07.324+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/fill_data.py
[2024-06-19T18:35:07.334+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/fill_data.py took 0.021 seconds
[2024-06-19T18:35:40.806+0000] {processor.py:161} INFO - Started process (PID=108) to work on /opt/airflow/dags/fill_data.py
[2024-06-19T18:35:40.807+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/fill_data.py for tasks to queue
[2024-06-19T18:35:40.809+0000] {logging_mixin.py:188} INFO - [2024-06-19T18:35:40.808+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/fill_data.py
[2024-06-19T18:35:40.814+0000] {logging_mixin.py:188} INFO - [2024-06-19T18:35:40.813+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/fill_data.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/fill_data.py", line 36
    del equipos_actuales(random_equipo)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: cannot delete function call
[2024-06-19T18:35:40.815+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/fill_data.py
[2024-06-19T18:35:40.827+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/fill_data.py took 0.028 seconds
[2024-06-19T18:36:14.297+0000] {processor.py:161} INFO - Started process (PID=115) to work on /opt/airflow/dags/fill_data.py
[2024-06-19T18:36:14.299+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/fill_data.py for tasks to queue
[2024-06-19T18:36:14.300+0000] {logging_mixin.py:188} INFO - [2024-06-19T18:36:14.300+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/fill_data.py
[2024-06-19T18:36:14.306+0000] {logging_mixin.py:188} INFO - [2024-06-19T18:36:14.305+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/fill_data.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/fill_data.py", line 36
    del equipos_actuales(random_equipo)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: cannot delete function call
[2024-06-19T18:36:14.307+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/fill_data.py
[2024-06-19T18:36:14.319+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/fill_data.py took 0.029 seconds
[2024-06-19T18:36:48.156+0000] {processor.py:161} INFO - Started process (PID=122) to work on /opt/airflow/dags/fill_data.py
[2024-06-19T18:36:48.157+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/fill_data.py for tasks to queue
[2024-06-19T18:36:48.159+0000] {logging_mixin.py:188} INFO - [2024-06-19T18:36:48.158+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/fill_data.py
[2024-06-19T18:36:48.165+0000] {logging_mixin.py:188} INFO - [2024-06-19T18:36:48.163+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/fill_data.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/fill_data.py", line 36
    del equipos_actuales(random_equipo)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: cannot delete function call
[2024-06-19T18:36:48.165+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/fill_data.py
[2024-06-19T18:36:48.178+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/fill_data.py took 0.027 seconds
[2024-06-19T18:37:21.907+0000] {processor.py:161} INFO - Started process (PID=129) to work on /opt/airflow/dags/fill_data.py
[2024-06-19T18:37:21.908+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/fill_data.py for tasks to queue
[2024-06-19T18:37:21.910+0000] {logging_mixin.py:188} INFO - [2024-06-19T18:37:21.910+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/fill_data.py
[2024-06-19T18:37:21.915+0000] {logging_mixin.py:188} INFO - [2024-06-19T18:37:21.914+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/fill_data.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/fill_data.py", line 36
    del equipos_actuales(random_equipo)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: cannot delete function call
[2024-06-19T18:37:21.915+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/fill_data.py
[2024-06-19T18:37:21.982+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/fill_data.py took 0.082 seconds
[2024-06-19T18:37:55.499+0000] {processor.py:161} INFO - Started process (PID=136) to work on /opt/airflow/dags/fill_data.py
[2024-06-19T18:37:55.499+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/fill_data.py for tasks to queue
[2024-06-19T18:37:55.501+0000] {logging_mixin.py:188} INFO - [2024-06-19T18:37:55.501+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/fill_data.py
[2024-06-19T18:37:55.505+0000] {logging_mixin.py:188} INFO - [2024-06-19T18:37:55.504+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/fill_data.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/fill_data.py", line 36
    del equipos_actuales(random_equipo)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: cannot delete function call
[2024-06-19T18:37:55.506+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/fill_data.py
[2024-06-19T18:37:55.518+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/fill_data.py took 0.024 seconds
[2024-06-19T18:38:29.002+0000] {processor.py:161} INFO - Started process (PID=143) to work on /opt/airflow/dags/fill_data.py
[2024-06-19T18:38:29.003+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/fill_data.py for tasks to queue
[2024-06-19T18:38:29.005+0000] {logging_mixin.py:188} INFO - [2024-06-19T18:38:29.005+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/fill_data.py
[2024-06-19T18:38:29.010+0000] {logging_mixin.py:188} INFO - [2024-06-19T18:38:29.009+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/fill_data.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/fill_data.py", line 36
    del equipos_actuales(random_equipo)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: cannot delete function call
[2024-06-19T18:38:29.010+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/fill_data.py
[2024-06-19T18:38:29.020+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/fill_data.py took 0.022 seconds
[2024-06-19T18:39:02.379+0000] {processor.py:161} INFO - Started process (PID=150) to work on /opt/airflow/dags/fill_data.py
[2024-06-19T18:39:02.380+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/fill_data.py for tasks to queue
[2024-06-19T18:39:02.382+0000] {logging_mixin.py:188} INFO - [2024-06-19T18:39:02.382+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/fill_data.py
[2024-06-19T18:39:02.389+0000] {logging_mixin.py:188} INFO - [2024-06-19T18:39:02.387+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/fill_data.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/fill_data.py", line 36
    del equipos_actuales(random_equipo)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: cannot delete function call
[2024-06-19T18:39:02.389+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/fill_data.py
[2024-06-19T18:39:02.400+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/fill_data.py took 0.029 seconds
[2024-06-19T18:39:35.985+0000] {processor.py:161} INFO - Started process (PID=157) to work on /opt/airflow/dags/fill_data.py
[2024-06-19T18:39:35.986+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/fill_data.py for tasks to queue
[2024-06-19T18:39:35.988+0000] {logging_mixin.py:188} INFO - [2024-06-19T18:39:35.987+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/fill_data.py
[2024-06-19T18:39:35.992+0000] {logging_mixin.py:188} INFO - [2024-06-19T18:39:35.992+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/fill_data.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/fill_data.py", line 36
    del equipos_actuales(random_equipo)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: cannot delete function call
[2024-06-19T18:39:35.993+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/fill_data.py
[2024-06-19T18:39:36.005+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/fill_data.py took 0.025 seconds
[2024-06-19T18:40:09.591+0000] {processor.py:161} INFO - Started process (PID=164) to work on /opt/airflow/dags/fill_data.py
[2024-06-19T18:40:09.592+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/fill_data.py for tasks to queue
[2024-06-19T18:40:09.594+0000] {logging_mixin.py:188} INFO - [2024-06-19T18:40:09.594+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/fill_data.py
[2024-06-19T18:40:09.601+0000] {logging_mixin.py:188} INFO - [2024-06-19T18:40:09.600+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/fill_data.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/fill_data.py", line 36
    del equipos_actuales(random_equipo)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: cannot delete function call
[2024-06-19T18:40:09.601+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/fill_data.py
[2024-06-19T18:40:09.615+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/fill_data.py took 0.031 seconds
[2024-06-19T18:40:43.007+0000] {processor.py:161} INFO - Started process (PID=171) to work on /opt/airflow/dags/fill_data.py
[2024-06-19T18:40:43.008+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/fill_data.py for tasks to queue
[2024-06-19T18:40:43.010+0000] {logging_mixin.py:188} INFO - [2024-06-19T18:40:43.010+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/fill_data.py
[2024-06-19T18:40:43.014+0000] {logging_mixin.py:188} INFO - [2024-06-19T18:40:43.014+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/fill_data.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/fill_data.py", line 36
    del equipos_actuales(random_equipo)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: cannot delete function call
[2024-06-19T18:40:43.015+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/fill_data.py
[2024-06-19T18:40:43.024+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/fill_data.py took 0.024 seconds
[2024-06-19T18:41:16.609+0000] {processor.py:161} INFO - Started process (PID=178) to work on /opt/airflow/dags/fill_data.py
[2024-06-19T18:41:16.611+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/fill_data.py for tasks to queue
[2024-06-19T18:41:16.613+0000] {logging_mixin.py:188} INFO - [2024-06-19T18:41:16.612+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/fill_data.py
[2024-06-19T18:41:16.619+0000] {logging_mixin.py:188} INFO - [2024-06-19T18:41:16.618+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/fill_data.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/fill_data.py", line 36
    del equipos_actuales(random_equipo)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: cannot delete function call
[2024-06-19T18:41:16.620+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/fill_data.py
[2024-06-19T18:41:16.635+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/fill_data.py took 0.033 seconds
[2024-06-19T18:41:50.474+0000] {processor.py:161} INFO - Started process (PID=185) to work on /opt/airflow/dags/fill_data.py
[2024-06-19T18:41:50.475+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/fill_data.py for tasks to queue
[2024-06-19T18:41:50.477+0000] {logging_mixin.py:188} INFO - [2024-06-19T18:41:50.476+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/fill_data.py
[2024-06-19T18:41:50.480+0000] {logging_mixin.py:188} INFO - [2024-06-19T18:41:50.480+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/fill_data.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/fill_data.py", line 36
    del equipos_actuales(random_equipo)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: cannot delete function call
[2024-06-19T18:41:50.481+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/fill_data.py
[2024-06-19T18:41:50.492+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/fill_data.py took 0.025 seconds
[2024-06-19T18:42:24.009+0000] {processor.py:161} INFO - Started process (PID=192) to work on /opt/airflow/dags/fill_data.py
[2024-06-19T18:42:24.010+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/fill_data.py for tasks to queue
[2024-06-19T18:42:24.011+0000] {logging_mixin.py:188} INFO - [2024-06-19T18:42:24.011+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/fill_data.py
[2024-06-19T18:42:24.016+0000] {logging_mixin.py:188} INFO - [2024-06-19T18:42:24.015+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/fill_data.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/fill_data.py", line 36
    del equipos_actuales(random_equipo)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: cannot delete function call
[2024-06-19T18:42:24.016+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/fill_data.py
[2024-06-19T18:42:24.027+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/fill_data.py took 0.023 seconds
[2024-06-19T18:42:39.102+0000] {processor.py:161} INFO - Started process (PID=193) to work on /opt/airflow/dags/fill_data.py
[2024-06-19T18:42:39.103+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/fill_data.py for tasks to queue
[2024-06-19T18:42:39.106+0000] {logging_mixin.py:188} INFO - [2024-06-19T18:42:39.106+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/fill_data.py
[2024-06-19T18:42:39.112+0000] {logging_mixin.py:188} INFO - [2024-06-19T18:42:39.111+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/fill_data.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/fill_data.py", line 36
    del equipos_actuales(random_equipo)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: cannot delete function call
[2024-06-19T18:42:39.113+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/fill_data.py
[2024-06-19T18:42:39.127+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/fill_data.py took 0.032 seconds
[2024-06-19T18:43:10.089+0000] {processor.py:161} INFO - Started process (PID=200) to work on /opt/airflow/dags/fill_data.py
[2024-06-19T18:43:10.091+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/fill_data.py for tasks to queue
[2024-06-19T18:43:10.093+0000] {logging_mixin.py:188} INFO - [2024-06-19T18:43:10.092+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/fill_data.py
[2024-06-19T18:43:10.100+0000] {logging_mixin.py:188} INFO - [2024-06-19T18:43:10.099+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/fill_data.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/fill_data.py", line 36
    del equipos_actuales(random_equipo)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: cannot delete function call
[2024-06-19T18:43:10.101+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/fill_data.py
[2024-06-19T18:43:10.116+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/fill_data.py took 0.035 seconds
[2024-06-19T18:43:40.573+0000] {processor.py:161} INFO - Started process (PID=207) to work on /opt/airflow/dags/fill_data.py
[2024-06-19T18:43:40.573+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/fill_data.py for tasks to queue
[2024-06-19T18:43:40.575+0000] {logging_mixin.py:188} INFO - [2024-06-19T18:43:40.574+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/fill_data.py
[2024-06-19T18:43:40.578+0000] {logging_mixin.py:188} INFO - [2024-06-19T18:43:40.577+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/fill_data.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/fill_data.py", line 36
    del equipos_actuales(random_equipo)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: cannot delete function call
[2024-06-19T18:43:40.578+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/fill_data.py
[2024-06-19T18:43:40.587+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/fill_data.py took 0.018 seconds
[2024-06-19T18:44:11.336+0000] {processor.py:161} INFO - Started process (PID=214) to work on /opt/airflow/dags/fill_data.py
[2024-06-19T18:44:11.338+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/fill_data.py for tasks to queue
[2024-06-19T18:44:11.340+0000] {logging_mixin.py:188} INFO - [2024-06-19T18:44:11.340+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/fill_data.py
[2024-06-19T18:44:11.347+0000] {logging_mixin.py:188} INFO - [2024-06-19T18:44:11.346+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/fill_data.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/fill_data.py", line 36
    del equipos_actuales(random_equipo)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: cannot delete function call
[2024-06-19T18:44:11.347+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/fill_data.py
[2024-06-19T18:44:11.361+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/fill_data.py took 0.032 seconds
[2024-06-19T18:44:15.347+0000] {processor.py:161} INFO - Started process (PID=215) to work on /opt/airflow/dags/fill_data.py
[2024-06-19T18:44:15.348+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/fill_data.py for tasks to queue
[2024-06-19T18:44:15.350+0000] {logging_mixin.py:188} INFO - [2024-06-19T18:44:15.350+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/fill_data.py
[2024-06-19T18:44:15.356+0000] {logging_mixin.py:188} INFO - [2024-06-19T18:44:15.356+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/fill_data.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/fill_data.py", line 41
    del equipos_actuales(random_equipo)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: cannot delete function call
[2024-06-19T18:44:15.357+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/fill_data.py
[2024-06-19T18:44:15.370+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/fill_data.py took 0.032 seconds
[2024-06-19T18:44:46.175+0000] {processor.py:161} INFO - Started process (PID=222) to work on /opt/airflow/dags/fill_data.py
[2024-06-19T18:44:46.176+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/fill_data.py for tasks to queue
[2024-06-19T18:44:46.178+0000] {logging_mixin.py:188} INFO - [2024-06-19T18:44:46.178+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/fill_data.py
[2024-06-19T18:44:46.185+0000] {logging_mixin.py:188} INFO - [2024-06-19T18:44:46.184+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/fill_data.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/fill_data.py", line 41
    del equipos_actuales(random_equipo)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: cannot delete function call
[2024-06-19T18:44:46.186+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/fill_data.py
[2024-06-19T18:44:46.200+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/fill_data.py took 0.033 seconds
[2024-06-19T18:45:16.874+0000] {processor.py:161} INFO - Started process (PID=229) to work on /opt/airflow/dags/fill_data.py
[2024-06-19T18:45:16.875+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/fill_data.py for tasks to queue
[2024-06-19T18:45:16.877+0000] {logging_mixin.py:188} INFO - [2024-06-19T18:45:16.877+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/fill_data.py
[2024-06-19T18:45:16.882+0000] {logging_mixin.py:188} INFO - [2024-06-19T18:45:16.881+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/fill_data.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/fill_data.py", line 41
    del equipos_actuales(random_equipo)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: cannot delete function call
[2024-06-19T18:45:16.883+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/fill_data.py
[2024-06-19T18:45:16.893+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/fill_data.py took 0.026 seconds
[2024-06-19T18:45:47.945+0000] {processor.py:161} INFO - Started process (PID=236) to work on /opt/airflow/dags/fill_data.py
[2024-06-19T18:45:47.947+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/fill_data.py for tasks to queue
[2024-06-19T18:45:47.950+0000] {logging_mixin.py:188} INFO - [2024-06-19T18:45:47.949+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/fill_data.py
[2024-06-19T18:45:47.955+0000] {logging_mixin.py:188} INFO - [2024-06-19T18:45:47.954+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/fill_data.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/fill_data.py", line 41
    del equipos_actuales(random_equipo)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: cannot delete function call
[2024-06-19T18:45:47.956+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/fill_data.py
[2024-06-19T18:45:47.969+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/fill_data.py took 0.032 seconds
[2024-06-19T18:46:20.886+0000] {processor.py:161} INFO - Started process (PID=243) to work on /opt/airflow/dags/fill_data.py
[2024-06-19T18:46:20.888+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/fill_data.py for tasks to queue
[2024-06-19T18:46:20.890+0000] {logging_mixin.py:188} INFO - [2024-06-19T18:46:20.890+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/fill_data.py
[2024-06-19T18:46:20.897+0000] {logging_mixin.py:188} INFO - [2024-06-19T18:46:20.896+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/fill_data.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/fill_data.py", line 41
    del equipos_actuales(random_equipo)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: cannot delete function call
[2024-06-19T18:46:20.897+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/fill_data.py
[2024-06-19T18:46:20.912+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/fill_data.py took 0.033 seconds
[2024-06-19T18:46:54.677+0000] {processor.py:161} INFO - Started process (PID=250) to work on /opt/airflow/dags/fill_data.py
[2024-06-19T18:46:54.678+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/fill_data.py for tasks to queue
[2024-06-19T18:46:54.680+0000] {logging_mixin.py:188} INFO - [2024-06-19T18:46:54.679+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/fill_data.py
[2024-06-19T18:46:54.685+0000] {logging_mixin.py:188} INFO - [2024-06-19T18:46:54.684+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/fill_data.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/fill_data.py", line 41
    del equipos_actuales(random_equipo)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: cannot delete function call
[2024-06-19T18:46:54.686+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/fill_data.py
[2024-06-19T18:46:54.699+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/fill_data.py took 0.029 seconds
[2024-06-19T18:47:28.437+0000] {processor.py:161} INFO - Started process (PID=257) to work on /opt/airflow/dags/fill_data.py
[2024-06-19T18:47:28.438+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/fill_data.py for tasks to queue
[2024-06-19T18:47:28.440+0000] {logging_mixin.py:188} INFO - [2024-06-19T18:47:28.440+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/fill_data.py
[2024-06-19T18:47:28.446+0000] {logging_mixin.py:188} INFO - [2024-06-19T18:47:28.445+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/fill_data.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/fill_data.py", line 41
    del equipos_actuales(random_equipo)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: cannot delete function call
[2024-06-19T18:47:28.446+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/fill_data.py
[2024-06-19T18:47:28.459+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/fill_data.py took 0.029 seconds
[2024-06-19T18:48:01.827+0000] {processor.py:161} INFO - Started process (PID=264) to work on /opt/airflow/dags/fill_data.py
[2024-06-19T18:48:01.828+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/fill_data.py for tasks to queue
[2024-06-19T18:48:01.831+0000] {logging_mixin.py:188} INFO - [2024-06-19T18:48:01.830+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/fill_data.py
[2024-06-19T18:48:01.837+0000] {logging_mixin.py:188} INFO - [2024-06-19T18:48:01.836+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/fill_data.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/fill_data.py", line 41
    del equipos_actuales(random_equipo)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: cannot delete function call
[2024-06-19T18:48:01.837+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/fill_data.py
[2024-06-19T18:48:01.852+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/fill_data.py took 0.032 seconds
[2024-06-19T18:48:36.398+0000] {processor.py:161} INFO - Started process (PID=271) to work on /opt/airflow/dags/fill_data.py
[2024-06-19T18:48:36.400+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/fill_data.py for tasks to queue
[2024-06-19T18:48:36.402+0000] {logging_mixin.py:188} INFO - [2024-06-19T18:48:36.402+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/fill_data.py
[2024-06-19T18:48:36.408+0000] {logging_mixin.py:188} INFO - [2024-06-19T18:48:36.407+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/fill_data.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/fill_data.py", line 41
    del equipos_actuales(random_equipo)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: cannot delete function call
[2024-06-19T18:48:36.409+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/fill_data.py
[2024-06-19T18:48:36.424+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/fill_data.py took 0.032 seconds
[2024-06-19T18:49:09.990+0000] {processor.py:161} INFO - Started process (PID=278) to work on /opt/airflow/dags/fill_data.py
[2024-06-19T18:49:09.991+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/fill_data.py for tasks to queue
[2024-06-19T18:49:09.992+0000] {logging_mixin.py:188} INFO - [2024-06-19T18:49:09.992+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/fill_data.py
[2024-06-19T18:49:09.996+0000] {logging_mixin.py:188} INFO - [2024-06-19T18:49:09.996+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/fill_data.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/fill_data.py", line 41
    del equipos_actuales(random_equipo)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: cannot delete function call
[2024-06-19T18:49:09.997+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/fill_data.py
[2024-06-19T18:49:10.005+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/fill_data.py took 0.020 seconds
[2024-06-19T18:49:43.466+0000] {processor.py:161} INFO - Started process (PID=285) to work on /opt/airflow/dags/fill_data.py
[2024-06-19T18:49:43.467+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/fill_data.py for tasks to queue
[2024-06-19T18:49:43.468+0000] {logging_mixin.py:188} INFO - [2024-06-19T18:49:43.468+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/fill_data.py
[2024-06-19T18:49:43.474+0000] {logging_mixin.py:188} INFO - [2024-06-19T18:49:43.473+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/fill_data.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/fill_data.py", line 41
    del equipos_actuales(random_equipo)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: cannot delete function call
[2024-06-19T18:49:43.474+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/fill_data.py
[2024-06-19T18:49:43.481+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/fill_data.py took 0.021 seconds
[2024-06-19T18:50:16.788+0000] {processor.py:161} INFO - Started process (PID=292) to work on /opt/airflow/dags/fill_data.py
[2024-06-19T18:50:16.789+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/fill_data.py for tasks to queue
[2024-06-19T18:50:16.789+0000] {logging_mixin.py:188} INFO - [2024-06-19T18:50:16.789+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/fill_data.py
[2024-06-19T18:50:16.792+0000] {logging_mixin.py:188} INFO - [2024-06-19T18:50:16.791+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/fill_data.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/fill_data.py", line 41
    del equipos_actuales(random_equipo)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: cannot delete function call
[2024-06-19T18:50:16.792+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/fill_data.py
[2024-06-19T18:50:16.798+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/fill_data.py took 0.012 seconds
[2024-06-19T18:50:50.368+0000] {processor.py:161} INFO - Started process (PID=299) to work on /opt/airflow/dags/fill_data.py
[2024-06-19T18:50:50.369+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/fill_data.py for tasks to queue
[2024-06-19T18:50:50.372+0000] {logging_mixin.py:188} INFO - [2024-06-19T18:50:50.371+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/fill_data.py
[2024-06-19T18:50:50.378+0000] {logging_mixin.py:188} INFO - [2024-06-19T18:50:50.377+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/fill_data.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/fill_data.py", line 41
    del equipos_actuales(random_equipo)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: cannot delete function call
[2024-06-19T18:50:50.378+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/fill_data.py
[2024-06-19T18:50:50.393+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/fill_data.py took 0.032 seconds
[2024-06-19T18:51:23.989+0000] {processor.py:161} INFO - Started process (PID=306) to work on /opt/airflow/dags/fill_data.py
[2024-06-19T18:51:23.990+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/fill_data.py for tasks to queue
[2024-06-19T18:51:23.991+0000] {logging_mixin.py:188} INFO - [2024-06-19T18:51:23.991+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/fill_data.py
[2024-06-19T18:51:23.995+0000] {logging_mixin.py:188} INFO - [2024-06-19T18:51:23.994+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/fill_data.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/fill_data.py", line 41
    del equipos_actuales(random_equipo)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: cannot delete function call
[2024-06-19T18:51:23.995+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/fill_data.py
[2024-06-19T18:51:24.008+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/fill_data.py took 0.025 seconds
[2024-06-19T18:51:58.405+0000] {processor.py:161} INFO - Started process (PID=313) to work on /opt/airflow/dags/fill_data.py
[2024-06-19T18:51:58.406+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/fill_data.py for tasks to queue
[2024-06-19T18:51:58.407+0000] {logging_mixin.py:188} INFO - [2024-06-19T18:51:58.407+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/fill_data.py
[2024-06-19T18:51:58.414+0000] {logging_mixin.py:188} INFO - [2024-06-19T18:51:58.413+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/fill_data.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/fill_data.py", line 41
    del equipos_actuales(random_equipo)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: cannot delete function call
[2024-06-19T18:51:58.415+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/fill_data.py
[2024-06-19T18:51:58.432+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/fill_data.py took 0.030 seconds
[2024-06-19T18:52:32.499+0000] {processor.py:161} INFO - Started process (PID=320) to work on /opt/airflow/dags/fill_data.py
[2024-06-19T18:52:32.500+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/fill_data.py for tasks to queue
[2024-06-19T18:52:32.502+0000] {logging_mixin.py:188} INFO - [2024-06-19T18:52:32.502+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/fill_data.py
[2024-06-19T18:52:32.508+0000] {logging_mixin.py:188} INFO - [2024-06-19T18:52:32.507+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/fill_data.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/fill_data.py", line 41
    del equipos_actuales(random_equipo)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: cannot delete function call
[2024-06-19T18:52:32.508+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/fill_data.py
[2024-06-19T18:52:32.522+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/fill_data.py took 0.032 seconds
[2024-06-19T18:53:06.144+0000] {processor.py:161} INFO - Started process (PID=327) to work on /opt/airflow/dags/fill_data.py
[2024-06-19T18:53:06.146+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/fill_data.py for tasks to queue
[2024-06-19T18:53:06.147+0000] {logging_mixin.py:188} INFO - [2024-06-19T18:53:06.147+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/fill_data.py
[2024-06-19T18:53:06.153+0000] {logging_mixin.py:188} INFO - [2024-06-19T18:53:06.152+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/fill_data.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/fill_data.py", line 41
    del equipos_actuales(random_equipo)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: cannot delete function call
[2024-06-19T18:53:06.154+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/fill_data.py
[2024-06-19T18:53:06.167+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/fill_data.py took 0.029 seconds
[2024-06-19T18:53:40.658+0000] {processor.py:161} INFO - Started process (PID=334) to work on /opt/airflow/dags/fill_data.py
[2024-06-19T18:53:40.659+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/fill_data.py for tasks to queue
[2024-06-19T18:53:40.661+0000] {logging_mixin.py:188} INFO - [2024-06-19T18:53:40.661+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/fill_data.py
[2024-06-19T18:53:40.667+0000] {logging_mixin.py:188} INFO - [2024-06-19T18:53:40.666+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/fill_data.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/fill_data.py", line 41
    del equipos_actuales(random_equipo)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: cannot delete function call
[2024-06-19T18:53:40.668+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/fill_data.py
[2024-06-19T18:53:40.682+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/fill_data.py took 0.032 seconds
[2024-06-19T18:54:14.216+0000] {processor.py:161} INFO - Started process (PID=341) to work on /opt/airflow/dags/fill_data.py
[2024-06-19T18:54:14.217+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/fill_data.py for tasks to queue
[2024-06-19T18:54:14.219+0000] {logging_mixin.py:188} INFO - [2024-06-19T18:54:14.218+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/fill_data.py
[2024-06-19T18:54:14.224+0000] {logging_mixin.py:188} INFO - [2024-06-19T18:54:14.223+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/fill_data.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/fill_data.py", line 41
    del equipos_actuales(random_equipo)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: cannot delete function call
[2024-06-19T18:54:14.225+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/fill_data.py
[2024-06-19T18:54:14.238+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/fill_data.py took 0.029 seconds
[2024-06-19T20:01:46.978+0000] {processor.py:161} INFO - Started process (PID=13) to work on /opt/airflow/dags/fill_data.py
[2024-06-19T20:01:46.979+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/fill_data.py for tasks to queue
[2024-06-19T20:01:46.980+0000] {logging_mixin.py:188} INFO - [2024-06-19T20:01:46.980+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/fill_data.py
[2024-06-19T20:01:46.983+0000] {logging_mixin.py:188} INFO - [2024-06-19T20:01:46.982+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/fill_data.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/fill_data.py", line 41
    del equipos_actuales(random_equipo)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: cannot delete function call
[2024-06-19T20:01:46.984+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/fill_data.py
[2024-06-19T20:01:46.996+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/fill_data.py took 0.021 seconds
[2024-06-19T20:02:18.061+0000] {processor.py:161} INFO - Started process (PID=26) to work on /opt/airflow/dags/fill_data.py
[2024-06-19T20:02:18.062+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/fill_data.py for tasks to queue
[2024-06-19T20:02:18.064+0000] {logging_mixin.py:188} INFO - [2024-06-19T20:02:18.064+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/fill_data.py
[2024-06-19T20:02:18.071+0000] {logging_mixin.py:188} INFO - [2024-06-19T20:02:18.070+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/fill_data.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/fill_data.py", line 41
    del equipos_actuales(random_equipo)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: cannot delete function call
[2024-06-19T20:02:18.071+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/fill_data.py
[2024-06-19T20:02:18.084+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/fill_data.py took 0.029 seconds
[2024-06-19T20:02:49.100+0000] {processor.py:161} INFO - Started process (PID=33) to work on /opt/airflow/dags/fill_data.py
[2024-06-19T20:02:49.101+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/fill_data.py for tasks to queue
[2024-06-19T20:02:49.102+0000] {logging_mixin.py:188} INFO - [2024-06-19T20:02:49.102+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/fill_data.py
[2024-06-19T20:02:49.108+0000] {logging_mixin.py:188} INFO - [2024-06-19T20:02:49.107+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/fill_data.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/fill_data.py", line 41
    del equipos_actuales(random_equipo)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: cannot delete function call
[2024-06-19T20:02:49.108+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/fill_data.py
[2024-06-19T20:02:49.121+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/fill_data.py took 0.028 seconds
[2024-06-19T20:03:20.244+0000] {processor.py:161} INFO - Started process (PID=40) to work on /opt/airflow/dags/fill_data.py
[2024-06-19T20:03:20.246+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/fill_data.py for tasks to queue
[2024-06-19T20:03:20.248+0000] {logging_mixin.py:188} INFO - [2024-06-19T20:03:20.248+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/fill_data.py
[2024-06-19T20:03:20.254+0000] {logging_mixin.py:188} INFO - [2024-06-19T20:03:20.253+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/fill_data.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/fill_data.py", line 41
    del equipos_actuales(random_equipo)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: cannot delete function call
[2024-06-19T20:03:20.255+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/fill_data.py
[2024-06-19T20:03:20.269+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/fill_data.py took 0.030 seconds
[2024-06-19T20:03:54.029+0000] {processor.py:161} INFO - Started process (PID=47) to work on /opt/airflow/dags/fill_data.py
[2024-06-19T20:03:54.031+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/fill_data.py for tasks to queue
[2024-06-19T20:03:54.033+0000] {logging_mixin.py:188} INFO - [2024-06-19T20:03:54.033+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/fill_data.py
[2024-06-19T20:03:54.040+0000] {logging_mixin.py:188} INFO - [2024-06-19T20:03:54.039+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/fill_data.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/fill_data.py", line 41
    del equipos_actuales(random_equipo)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: cannot delete function call
[2024-06-19T20:03:54.040+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/fill_data.py
[2024-06-19T20:03:54.054+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/fill_data.py took 0.031 seconds
[2024-06-19T20:04:27.606+0000] {processor.py:161} INFO - Started process (PID=54) to work on /opt/airflow/dags/fill_data.py
[2024-06-19T20:04:27.607+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/fill_data.py for tasks to queue
[2024-06-19T20:04:27.610+0000] {logging_mixin.py:188} INFO - [2024-06-19T20:04:27.609+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/fill_data.py
[2024-06-19T20:04:27.616+0000] {logging_mixin.py:188} INFO - [2024-06-19T20:04:27.615+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/fill_data.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/fill_data.py", line 41
    del equipos_actuales(random_equipo)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: cannot delete function call
[2024-06-19T20:04:27.616+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/fill_data.py
[2024-06-19T20:04:27.629+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/fill_data.py took 0.030 seconds
[2024-06-19T20:05:01.201+0000] {processor.py:161} INFO - Started process (PID=61) to work on /opt/airflow/dags/fill_data.py
[2024-06-19T20:05:01.202+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/fill_data.py for tasks to queue
[2024-06-19T20:05:01.204+0000] {logging_mixin.py:188} INFO - [2024-06-19T20:05:01.204+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/fill_data.py
[2024-06-19T20:05:01.210+0000] {logging_mixin.py:188} INFO - [2024-06-19T20:05:01.209+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/fill_data.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/fill_data.py", line 41
    del equipos_actuales(random_equipo)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: cannot delete function call
[2024-06-19T20:05:01.211+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/fill_data.py
[2024-06-19T20:05:01.226+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/fill_data.py took 0.032 seconds
[2024-06-19T20:05:35.011+0000] {processor.py:161} INFO - Started process (PID=68) to work on /opt/airflow/dags/fill_data.py
[2024-06-19T20:05:35.012+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/fill_data.py for tasks to queue
[2024-06-19T20:05:35.014+0000] {logging_mixin.py:188} INFO - [2024-06-19T20:05:35.013+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/fill_data.py
[2024-06-19T20:05:35.019+0000] {logging_mixin.py:188} INFO - [2024-06-19T20:05:35.018+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/fill_data.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/fill_data.py", line 41
    del equipos_actuales(random_equipo)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: cannot delete function call
[2024-06-19T20:05:35.020+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/fill_data.py
[2024-06-19T20:05:35.032+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/fill_data.py took 0.028 seconds
[2024-06-19T20:06:09.450+0000] {processor.py:161} INFO - Started process (PID=75) to work on /opt/airflow/dags/fill_data.py
[2024-06-19T20:06:09.452+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/fill_data.py for tasks to queue
[2024-06-19T20:06:09.454+0000] {logging_mixin.py:188} INFO - [2024-06-19T20:06:09.453+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/fill_data.py
[2024-06-19T20:06:09.461+0000] {logging_mixin.py:188} INFO - [2024-06-19T20:06:09.459+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/fill_data.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/fill_data.py", line 41
    del equipos_actuales(random_equipo)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: cannot delete function call
[2024-06-19T20:06:09.461+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/fill_data.py
[2024-06-19T20:06:09.475+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/fill_data.py took 0.034 seconds
[2024-06-19T20:06:43.026+0000] {processor.py:161} INFO - Started process (PID=82) to work on /opt/airflow/dags/fill_data.py
[2024-06-19T20:06:43.027+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/fill_data.py for tasks to queue
[2024-06-19T20:06:43.028+0000] {logging_mixin.py:188} INFO - [2024-06-19T20:06:43.028+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/fill_data.py
[2024-06-19T20:06:43.034+0000] {logging_mixin.py:188} INFO - [2024-06-19T20:06:43.033+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/fill_data.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/fill_data.py", line 41
    del equipos_actuales(random_equipo)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: cannot delete function call
[2024-06-19T20:06:43.034+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/fill_data.py
[2024-06-19T20:06:43.050+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/fill_data.py took 0.029 seconds
[2024-06-19T20:07:16.732+0000] {processor.py:161} INFO - Started process (PID=89) to work on /opt/airflow/dags/fill_data.py
[2024-06-19T20:07:16.733+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/fill_data.py for tasks to queue
[2024-06-19T20:07:16.735+0000] {logging_mixin.py:188} INFO - [2024-06-19T20:07:16.735+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/fill_data.py
[2024-06-19T20:07:16.741+0000] {logging_mixin.py:188} INFO - [2024-06-19T20:07:16.740+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/fill_data.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/fill_data.py", line 41
    del equipos_actuales(random_equipo)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: cannot delete function call
[2024-06-19T20:07:16.741+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/fill_data.py
[2024-06-19T20:07:16.754+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/fill_data.py took 0.029 seconds
[2024-06-19T20:07:50.327+0000] {processor.py:161} INFO - Started process (PID=96) to work on /opt/airflow/dags/fill_data.py
[2024-06-19T20:07:50.328+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/fill_data.py for tasks to queue
[2024-06-19T20:07:50.330+0000] {logging_mixin.py:188} INFO - [2024-06-19T20:07:50.330+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/fill_data.py
[2024-06-19T20:07:50.336+0000] {logging_mixin.py:188} INFO - [2024-06-19T20:07:50.335+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/fill_data.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/fill_data.py", line 41
    del equipos_actuales(random_equipo)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: cannot delete function call
[2024-06-19T20:07:50.337+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/fill_data.py
[2024-06-19T20:07:50.350+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/fill_data.py took 0.030 seconds
[2024-06-19T20:08:23.821+0000] {processor.py:161} INFO - Started process (PID=103) to work on /opt/airflow/dags/fill_data.py
[2024-06-19T20:08:23.822+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/fill_data.py for tasks to queue
[2024-06-19T20:08:23.824+0000] {logging_mixin.py:188} INFO - [2024-06-19T20:08:23.823+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/fill_data.py
[2024-06-19T20:08:23.830+0000] {logging_mixin.py:188} INFO - [2024-06-19T20:08:23.829+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/fill_data.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/fill_data.py", line 41
    del equipos_actuales(random_equipo)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: cannot delete function call
[2024-06-19T20:08:23.830+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/fill_data.py
[2024-06-19T20:08:23.843+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/fill_data.py took 0.029 seconds
[2024-06-19T20:08:57.818+0000] {processor.py:161} INFO - Started process (PID=110) to work on /opt/airflow/dags/fill_data.py
[2024-06-19T20:08:57.819+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/fill_data.py for tasks to queue
[2024-06-19T20:08:57.820+0000] {logging_mixin.py:188} INFO - [2024-06-19T20:08:57.820+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/fill_data.py
[2024-06-19T20:08:57.825+0000] {logging_mixin.py:188} INFO - [2024-06-19T20:08:57.824+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/fill_data.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/fill_data.py", line 41
    del equipos_actuales(random_equipo)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: cannot delete function call
[2024-06-19T20:08:57.826+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/fill_data.py
[2024-06-19T20:08:57.836+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/fill_data.py took 0.022 seconds
[2024-06-19T20:09:31.408+0000] {processor.py:161} INFO - Started process (PID=117) to work on /opt/airflow/dags/fill_data.py
[2024-06-19T20:09:31.409+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/fill_data.py for tasks to queue
[2024-06-19T20:09:31.411+0000] {logging_mixin.py:188} INFO - [2024-06-19T20:09:31.411+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/fill_data.py
[2024-06-19T20:09:31.417+0000] {logging_mixin.py:188} INFO - [2024-06-19T20:09:31.416+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/fill_data.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/fill_data.py", line 41
    del equipos_actuales(random_equipo)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: cannot delete function call
[2024-06-19T20:09:31.418+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/fill_data.py
[2024-06-19T20:09:31.486+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/fill_data.py took 0.085 seconds
[2024-06-19T20:10:04.911+0000] {processor.py:161} INFO - Started process (PID=124) to work on /opt/airflow/dags/fill_data.py
[2024-06-19T20:10:04.912+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/fill_data.py for tasks to queue
[2024-06-19T20:10:04.914+0000] {logging_mixin.py:188} INFO - [2024-06-19T20:10:04.914+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/fill_data.py
[2024-06-19T20:10:04.918+0000] {logging_mixin.py:188} INFO - [2024-06-19T20:10:04.918+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/fill_data.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/fill_data.py", line 41
    del equipos_actuales(random_equipo)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: cannot delete function call
[2024-06-19T20:10:04.919+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/fill_data.py
[2024-06-19T20:10:04.928+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/fill_data.py took 0.023 seconds
[2024-06-19T20:10:38.365+0000] {processor.py:161} INFO - Started process (PID=131) to work on /opt/airflow/dags/fill_data.py
[2024-06-19T20:10:38.366+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/fill_data.py for tasks to queue
[2024-06-19T20:10:38.366+0000] {logging_mixin.py:188} INFO - [2024-06-19T20:10:38.366+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/fill_data.py
[2024-06-19T20:10:38.369+0000] {logging_mixin.py:188} INFO - [2024-06-19T20:10:38.368+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/fill_data.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/fill_data.py", line 41
    del equipos_actuales(random_equipo)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: cannot delete function call
[2024-06-19T20:10:38.369+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/fill_data.py
[2024-06-19T20:10:38.376+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/fill_data.py took 0.013 seconds
[2024-06-19T20:11:11.787+0000] {processor.py:161} INFO - Started process (PID=138) to work on /opt/airflow/dags/fill_data.py
[2024-06-19T20:11:11.788+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/fill_data.py for tasks to queue
[2024-06-19T20:11:11.790+0000] {logging_mixin.py:188} INFO - [2024-06-19T20:11:11.790+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/fill_data.py
[2024-06-19T20:11:11.796+0000] {logging_mixin.py:188} INFO - [2024-06-19T20:11:11.795+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/fill_data.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/fill_data.py", line 41
    del equipos_actuales(random_equipo)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: cannot delete function call
[2024-06-19T20:11:11.797+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/fill_data.py
[2024-06-19T20:11:11.808+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/fill_data.py took 0.028 seconds
[2024-06-19T20:11:45.446+0000] {processor.py:161} INFO - Started process (PID=145) to work on /opt/airflow/dags/fill_data.py
[2024-06-19T20:11:45.446+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/fill_data.py for tasks to queue
[2024-06-19T20:11:45.448+0000] {logging_mixin.py:188} INFO - [2024-06-19T20:11:45.447+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/fill_data.py
[2024-06-19T20:11:45.452+0000] {logging_mixin.py:188} INFO - [2024-06-19T20:11:45.451+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/fill_data.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/fill_data.py", line 41
    del equipos_actuales(random_equipo)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: cannot delete function call
[2024-06-19T20:11:45.452+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/fill_data.py
[2024-06-19T20:11:45.462+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/fill_data.py took 0.022 seconds
[2024-06-19T20:12:18.926+0000] {processor.py:161} INFO - Started process (PID=152) to work on /opt/airflow/dags/fill_data.py
[2024-06-19T20:12:18.927+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/fill_data.py for tasks to queue
[2024-06-19T20:12:18.929+0000] {logging_mixin.py:188} INFO - [2024-06-19T20:12:18.928+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/fill_data.py
[2024-06-19T20:12:18.935+0000] {logging_mixin.py:188} INFO - [2024-06-19T20:12:18.934+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/fill_data.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/fill_data.py", line 41
    del equipos_actuales(random_equipo)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: cannot delete function call
[2024-06-19T20:12:18.936+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/fill_data.py
[2024-06-19T20:12:18.949+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/fill_data.py took 0.030 seconds
[2024-06-19T20:12:52.546+0000] {processor.py:161} INFO - Started process (PID=159) to work on /opt/airflow/dags/fill_data.py
[2024-06-19T20:12:52.547+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/fill_data.py for tasks to queue
[2024-06-19T20:12:52.549+0000] {logging_mixin.py:188} INFO - [2024-06-19T20:12:52.548+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/fill_data.py
[2024-06-19T20:12:52.553+0000] {logging_mixin.py:188} INFO - [2024-06-19T20:12:52.553+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/fill_data.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/fill_data.py", line 41
    del equipos_actuales(random_equipo)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: cannot delete function call
[2024-06-19T20:12:52.554+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/fill_data.py
[2024-06-19T20:12:52.565+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/fill_data.py took 0.026 seconds
[2024-06-19T20:13:26.596+0000] {processor.py:161} INFO - Started process (PID=166) to work on /opt/airflow/dags/fill_data.py
[2024-06-19T20:13:26.597+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/fill_data.py for tasks to queue
[2024-06-19T20:13:26.599+0000] {logging_mixin.py:188} INFO - [2024-06-19T20:13:26.599+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/fill_data.py
[2024-06-19T20:13:26.605+0000] {logging_mixin.py:188} INFO - [2024-06-19T20:13:26.604+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/fill_data.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/fill_data.py", line 41
    del equipos_actuales(random_equipo)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: cannot delete function call
[2024-06-19T20:13:26.606+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/fill_data.py
[2024-06-19T20:13:26.620+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/fill_data.py took 0.031 seconds
[2024-06-19T20:13:59.882+0000] {processor.py:161} INFO - Started process (PID=173) to work on /opt/airflow/dags/fill_data.py
[2024-06-19T20:13:59.883+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/fill_data.py for tasks to queue
[2024-06-19T20:13:59.885+0000] {logging_mixin.py:188} INFO - [2024-06-19T20:13:59.885+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/fill_data.py
[2024-06-19T20:13:59.891+0000] {logging_mixin.py:188} INFO - [2024-06-19T20:13:59.890+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/fill_data.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/fill_data.py", line 41
    del equipos_actuales(random_equipo)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: cannot delete function call
[2024-06-19T20:13:59.892+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/fill_data.py
[2024-06-19T20:13:59.904+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/fill_data.py took 0.029 seconds
[2024-06-19T20:14:33.538+0000] {processor.py:161} INFO - Started process (PID=180) to work on /opt/airflow/dags/fill_data.py
[2024-06-19T20:14:33.539+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/fill_data.py for tasks to queue
[2024-06-19T20:14:33.541+0000] {logging_mixin.py:188} INFO - [2024-06-19T20:14:33.541+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/fill_data.py
[2024-06-19T20:14:33.547+0000] {logging_mixin.py:188} INFO - [2024-06-19T20:14:33.546+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/fill_data.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/fill_data.py", line 41
    del equipos_actuales(random_equipo)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: cannot delete function call
[2024-06-19T20:14:33.548+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/fill_data.py
[2024-06-19T20:14:33.562+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/fill_data.py took 0.030 seconds
[2024-06-19T20:15:06.957+0000] {processor.py:161} INFO - Started process (PID=187) to work on /opt/airflow/dags/fill_data.py
[2024-06-19T20:15:06.959+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/fill_data.py for tasks to queue
[2024-06-19T20:15:06.961+0000] {logging_mixin.py:188} INFO - [2024-06-19T20:15:06.960+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/fill_data.py
[2024-06-19T20:15:06.967+0000] {logging_mixin.py:188} INFO - [2024-06-19T20:15:06.966+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/fill_data.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/fill_data.py", line 41
    del equipos_actuales(random_equipo)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: cannot delete function call
[2024-06-19T20:15:06.967+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/fill_data.py
[2024-06-19T20:15:06.982+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/fill_data.py took 0.031 seconds
[2024-06-19T20:15:41.929+0000] {processor.py:161} INFO - Started process (PID=194) to work on /opt/airflow/dags/fill_data.py
[2024-06-19T20:15:41.931+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/fill_data.py for tasks to queue
[2024-06-19T20:15:41.933+0000] {logging_mixin.py:188} INFO - [2024-06-19T20:15:41.933+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/fill_data.py
[2024-06-19T20:15:41.940+0000] {logging_mixin.py:188} INFO - [2024-06-19T20:15:41.939+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/fill_data.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/fill_data.py", line 41
    del equipos_actuales(random_equipo)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: cannot delete function call
[2024-06-19T20:15:41.941+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/fill_data.py
[2024-06-19T20:15:41.956+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/fill_data.py took 0.036 seconds
[2024-06-19T20:20:40.167+0000] {processor.py:161} INFO - Started process (PID=195) to work on /opt/airflow/dags/fill_data.py
[2024-06-19T20:20:40.168+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/fill_data.py for tasks to queue
[2024-06-19T20:20:40.169+0000] {logging_mixin.py:188} INFO - [2024-06-19T20:20:40.169+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/fill_data.py
[2024-06-19T20:20:40.173+0000] {logging_mixin.py:188} INFO - [2024-06-19T20:20:40.173+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/fill_data.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/fill_data.py", line 41
    del equipos_actuales(random_equipo)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: cannot delete function call
[2024-06-19T20:20:40.174+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/fill_data.py
[2024-06-19T20:20:40.187+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/fill_data.py took 0.026 seconds
[2024-06-19T20:21:10.997+0000] {processor.py:161} INFO - Started process (PID=202) to work on /opt/airflow/dags/fill_data.py
[2024-06-19T20:21:10.998+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/fill_data.py for tasks to queue
[2024-06-19T20:21:11.001+0000] {logging_mixin.py:188} INFO - [2024-06-19T20:21:11.000+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/fill_data.py
[2024-06-19T20:21:11.007+0000] {logging_mixin.py:188} INFO - [2024-06-19T20:21:11.006+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/fill_data.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/fill_data.py", line 41
    del equipos_actuales(random_equipo)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: cannot delete function call
[2024-06-19T20:21:11.008+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/fill_data.py
[2024-06-19T20:21:11.023+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/fill_data.py took 0.033 seconds
[2024-06-19T20:21:41.407+0000] {processor.py:161} INFO - Started process (PID=209) to work on /opt/airflow/dags/fill_data.py
[2024-06-19T20:21:41.408+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/fill_data.py for tasks to queue
[2024-06-19T20:21:41.410+0000] {logging_mixin.py:188} INFO - [2024-06-19T20:21:41.410+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/fill_data.py
[2024-06-19T20:21:41.417+0000] {logging_mixin.py:188} INFO - [2024-06-19T20:21:41.416+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/fill_data.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/fill_data.py", line 41
    del equipos_actuales(random_equipo)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: cannot delete function call
[2024-06-19T20:21:41.418+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/fill_data.py
[2024-06-19T20:21:41.432+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/fill_data.py took 0.032 seconds
[2024-06-19T20:22:11.993+0000] {processor.py:161} INFO - Started process (PID=216) to work on /opt/airflow/dags/fill_data.py
[2024-06-19T20:22:11.995+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/fill_data.py for tasks to queue
[2024-06-19T20:22:11.998+0000] {logging_mixin.py:188} INFO - [2024-06-19T20:22:11.997+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/fill_data.py
[2024-06-19T20:22:12.003+0000] {logging_mixin.py:188} INFO - [2024-06-19T20:22:12.002+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/fill_data.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/fill_data.py", line 41
    del equipos_actuales(random_equipo)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: cannot delete function call
[2024-06-19T20:22:12.004+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/fill_data.py
[2024-06-19T20:22:12.018+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/fill_data.py took 0.032 seconds
[2024-06-19T20:22:42.438+0000] {processor.py:161} INFO - Started process (PID=223) to work on /opt/airflow/dags/fill_data.py
[2024-06-19T20:22:42.439+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/fill_data.py for tasks to queue
[2024-06-19T20:22:42.441+0000] {logging_mixin.py:188} INFO - [2024-06-19T20:22:42.440+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/fill_data.py
[2024-06-19T20:22:42.446+0000] {logging_mixin.py:188} INFO - [2024-06-19T20:22:42.445+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/fill_data.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/fill_data.py", line 41
    del equipos_actuales(random_equipo)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: cannot delete function call
[2024-06-19T20:22:42.447+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/fill_data.py
[2024-06-19T20:22:42.461+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/fill_data.py took 0.028 seconds
[2024-06-19T20:23:13.083+0000] {processor.py:161} INFO - Started process (PID=230) to work on /opt/airflow/dags/fill_data.py
[2024-06-19T20:23:13.085+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/fill_data.py for tasks to queue
[2024-06-19T20:23:13.087+0000] {logging_mixin.py:188} INFO - [2024-06-19T20:23:13.087+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/fill_data.py
[2024-06-19T20:23:13.094+0000] {logging_mixin.py:188} INFO - [2024-06-19T20:23:13.093+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/fill_data.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/fill_data.py", line 41
    del equipos_actuales(random_equipo)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: cannot delete function call
[2024-06-19T20:23:13.095+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/fill_data.py
[2024-06-19T20:23:13.110+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/fill_data.py took 0.033 seconds
[2024-06-19T20:23:43.403+0000] {processor.py:161} INFO - Started process (PID=237) to work on /opt/airflow/dags/fill_data.py
[2024-06-19T20:23:43.404+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/fill_data.py for tasks to queue
[2024-06-19T20:23:43.407+0000] {logging_mixin.py:188} INFO - [2024-06-19T20:23:43.407+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/fill_data.py
[2024-06-19T20:23:43.414+0000] {logging_mixin.py:188} INFO - [2024-06-19T20:23:43.412+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/fill_data.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/fill_data.py", line 41
    del equipos_actuales(random_equipo)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: cannot delete function call
[2024-06-19T20:23:43.414+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/fill_data.py
[2024-06-19T20:23:43.428+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/fill_data.py took 0.032 seconds
[2024-06-19T20:24:14.259+0000] {processor.py:161} INFO - Started process (PID=244) to work on /opt/airflow/dags/fill_data.py
[2024-06-19T20:24:14.260+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/fill_data.py for tasks to queue
[2024-06-19T20:24:14.263+0000] {logging_mixin.py:188} INFO - [2024-06-19T20:24:14.262+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/fill_data.py
[2024-06-19T20:24:14.269+0000] {logging_mixin.py:188} INFO - [2024-06-19T20:24:14.268+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/fill_data.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/fill_data.py", line 41
    del equipos_actuales(random_equipo)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: cannot delete function call
[2024-06-19T20:24:14.270+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/fill_data.py
[2024-06-19T20:24:14.284+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/fill_data.py took 0.032 seconds
[2024-06-19T20:24:44.749+0000] {processor.py:161} INFO - Started process (PID=251) to work on /opt/airflow/dags/fill_data.py
[2024-06-19T20:24:44.750+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/fill_data.py for tasks to queue
[2024-06-19T20:24:44.753+0000] {logging_mixin.py:188} INFO - [2024-06-19T20:24:44.753+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/fill_data.py
[2024-06-19T20:24:44.761+0000] {logging_mixin.py:188} INFO - [2024-06-19T20:24:44.759+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/fill_data.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/fill_data.py", line 41
    del equipos_actuales(random_equipo)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: cannot delete function call
[2024-06-19T20:24:44.761+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/fill_data.py
[2024-06-19T20:24:44.777+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/fill_data.py took 0.034 seconds
[2024-06-19T20:25:15.004+0000] {processor.py:161} INFO - Started process (PID=258) to work on /opt/airflow/dags/fill_data.py
[2024-06-19T20:25:15.006+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/fill_data.py for tasks to queue
[2024-06-19T20:25:15.009+0000] {logging_mixin.py:188} INFO - [2024-06-19T20:25:15.008+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/fill_data.py
[2024-06-19T20:25:15.015+0000] {logging_mixin.py:188} INFO - [2024-06-19T20:25:15.014+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/fill_data.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/fill_data.py", line 41
    del equipos_actuales(random_equipo)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: cannot delete function call
[2024-06-19T20:25:15.016+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/fill_data.py
[2024-06-19T20:25:15.030+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/fill_data.py took 0.033 seconds
[2024-06-19T20:25:48.472+0000] {processor.py:161} INFO - Started process (PID=265) to work on /opt/airflow/dags/fill_data.py
[2024-06-19T20:25:48.473+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/fill_data.py for tasks to queue
[2024-06-19T20:25:48.475+0000] {logging_mixin.py:188} INFO - [2024-06-19T20:25:48.475+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/fill_data.py
[2024-06-19T20:25:48.482+0000] {logging_mixin.py:188} INFO - [2024-06-19T20:25:48.481+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/fill_data.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/fill_data.py", line 41
    del equipos_actuales(random_equipo)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: cannot delete function call
[2024-06-19T20:25:48.482+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/fill_data.py
[2024-06-19T20:25:48.495+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/fill_data.py took 0.030 seconds
[2024-06-19T20:26:22.315+0000] {processor.py:161} INFO - Started process (PID=272) to work on /opt/airflow/dags/fill_data.py
[2024-06-19T20:26:22.316+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/fill_data.py for tasks to queue
[2024-06-19T20:26:22.318+0000] {logging_mixin.py:188} INFO - [2024-06-19T20:26:22.318+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/fill_data.py
[2024-06-19T20:26:22.325+0000] {logging_mixin.py:188} INFO - [2024-06-19T20:26:22.323+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/fill_data.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/fill_data.py", line 41
    del equipos_actuales(random_equipo)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: cannot delete function call
[2024-06-19T20:26:22.326+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/fill_data.py
[2024-06-19T20:26:22.337+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/fill_data.py took 0.027 seconds
[2024-06-19T20:26:56.244+0000] {processor.py:161} INFO - Started process (PID=279) to work on /opt/airflow/dags/fill_data.py
[2024-06-19T20:26:56.245+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/fill_data.py for tasks to queue
[2024-06-19T20:26:56.248+0000] {logging_mixin.py:188} INFO - [2024-06-19T20:26:56.248+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/fill_data.py
[2024-06-19T20:26:56.255+0000] {logging_mixin.py:188} INFO - [2024-06-19T20:26:56.253+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/fill_data.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/fill_data.py", line 41
    del equipos_actuales(random_equipo)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: cannot delete function call
[2024-06-19T20:26:56.256+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/fill_data.py
[2024-06-19T20:26:56.271+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/fill_data.py took 0.034 seconds
[2024-06-19T20:27:29.713+0000] {processor.py:161} INFO - Started process (PID=286) to work on /opt/airflow/dags/fill_data.py
[2024-06-19T20:27:29.714+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/fill_data.py for tasks to queue
[2024-06-19T20:27:29.717+0000] {logging_mixin.py:188} INFO - [2024-06-19T20:27:29.716+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/fill_data.py
[2024-06-19T20:27:29.723+0000] {logging_mixin.py:188} INFO - [2024-06-19T20:27:29.722+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/fill_data.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/fill_data.py", line 41
    del equipos_actuales(random_equipo)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: cannot delete function call
[2024-06-19T20:27:29.723+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/fill_data.py
[2024-06-19T20:27:29.737+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/fill_data.py took 0.031 seconds
[2024-06-19T20:28:03.301+0000] {processor.py:161} INFO - Started process (PID=293) to work on /opt/airflow/dags/fill_data.py
[2024-06-19T20:28:03.302+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/fill_data.py for tasks to queue
[2024-06-19T20:28:03.304+0000] {logging_mixin.py:188} INFO - [2024-06-19T20:28:03.303+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/fill_data.py
[2024-06-19T20:28:03.309+0000] {logging_mixin.py:188} INFO - [2024-06-19T20:28:03.308+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/fill_data.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/fill_data.py", line 41
    del equipos_actuales(random_equipo)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: cannot delete function call
[2024-06-19T20:28:03.310+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/fill_data.py
[2024-06-19T20:28:03.323+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/fill_data.py took 0.029 seconds
[2024-06-19T20:28:37.280+0000] {processor.py:161} INFO - Started process (PID=300) to work on /opt/airflow/dags/fill_data.py
[2024-06-19T20:28:37.281+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/fill_data.py for tasks to queue
[2024-06-19T20:28:37.283+0000] {logging_mixin.py:188} INFO - [2024-06-19T20:28:37.283+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/fill_data.py
[2024-06-19T20:28:37.289+0000] {logging_mixin.py:188} INFO - [2024-06-19T20:28:37.288+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/fill_data.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/fill_data.py", line 41
    del equipos_actuales(random_equipo)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: cannot delete function call
[2024-06-19T20:28:37.290+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/fill_data.py
[2024-06-19T20:28:37.303+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/fill_data.py took 0.029 seconds
[2024-06-19T20:29:10.621+0000] {processor.py:161} INFO - Started process (PID=307) to work on /opt/airflow/dags/fill_data.py
[2024-06-19T20:29:10.622+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/fill_data.py for tasks to queue
[2024-06-19T20:29:10.623+0000] {logging_mixin.py:188} INFO - [2024-06-19T20:29:10.622+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/fill_data.py
[2024-06-19T20:29:10.625+0000] {logging_mixin.py:188} INFO - [2024-06-19T20:29:10.624+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/fill_data.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/fill_data.py", line 41
    del equipos_actuales(random_equipo)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: cannot delete function call
[2024-06-19T20:29:10.625+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/fill_data.py
[2024-06-19T20:29:10.631+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/fill_data.py took 0.012 seconds
[2024-06-19T20:29:44.112+0000] {processor.py:161} INFO - Started process (PID=314) to work on /opt/airflow/dags/fill_data.py
[2024-06-19T20:29:44.113+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/fill_data.py for tasks to queue
[2024-06-19T20:29:44.114+0000] {logging_mixin.py:188} INFO - [2024-06-19T20:29:44.114+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/fill_data.py
[2024-06-19T20:29:44.118+0000] {logging_mixin.py:188} INFO - [2024-06-19T20:29:44.117+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/fill_data.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/fill_data.py", line 41
    del equipos_actuales(random_equipo)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: cannot delete function call
[2024-06-19T20:29:44.118+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/fill_data.py
[2024-06-19T20:29:44.130+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/fill_data.py took 0.022 seconds
[2024-06-19T20:31:29.093+0000] {processor.py:161} INFO - Started process (PID=315) to work on /opt/airflow/dags/fill_data.py
[2024-06-19T20:31:29.094+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/fill_data.py for tasks to queue
[2024-06-19T20:31:29.095+0000] {logging_mixin.py:188} INFO - [2024-06-19T20:31:29.095+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/fill_data.py
[2024-06-19T20:31:29.099+0000] {logging_mixin.py:188} INFO - [2024-06-19T20:31:29.099+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/fill_data.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/fill_data.py", line 41
    del equipos_actuales(random_equipo)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: cannot delete function call
[2024-06-19T20:31:29.100+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/fill_data.py
[2024-06-19T20:31:29.110+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/fill_data.py took 0.020 seconds
[2024-06-19T20:40:49.803+0000] {processor.py:161} INFO - Started process (PID=322) to work on /opt/airflow/dags/fill_data.py
[2024-06-19T20:40:49.804+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/fill_data.py for tasks to queue
[2024-06-19T20:40:49.805+0000] {logging_mixin.py:188} INFO - [2024-06-19T20:40:49.805+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/fill_data.py
[2024-06-19T20:40:49.810+0000] {logging_mixin.py:188} INFO - [2024-06-19T20:40:49.809+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/fill_data.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/fill_data.py", line 41
    del equipos_actuales(random_equipo)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: cannot delete function call
[2024-06-19T20:40:49.810+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/fill_data.py
[2024-06-19T20:40:49.821+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/fill_data.py took 0.023 seconds
[2024-06-19T20:41:20.618+0000] {processor.py:161} INFO - Started process (PID=329) to work on /opt/airflow/dags/fill_data.py
[2024-06-19T20:41:20.619+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/fill_data.py for tasks to queue
[2024-06-19T20:41:20.622+0000] {logging_mixin.py:188} INFO - [2024-06-19T20:41:20.622+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/fill_data.py
[2024-06-19T20:41:20.627+0000] {logging_mixin.py:188} INFO - [2024-06-19T20:41:20.626+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/fill_data.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/fill_data.py", line 41
    del equipos_actuales(random_equipo)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: cannot delete function call
[2024-06-19T20:41:20.628+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/fill_data.py
[2024-06-19T20:41:20.639+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/fill_data.py took 0.028 seconds
[2024-06-19T20:41:50.781+0000] {processor.py:161} INFO - Started process (PID=336) to work on /opt/airflow/dags/fill_data.py
[2024-06-19T20:41:50.782+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/fill_data.py for tasks to queue
[2024-06-19T20:41:50.784+0000] {logging_mixin.py:188} INFO - [2024-06-19T20:41:50.784+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/fill_data.py
[2024-06-19T20:41:50.790+0000] {logging_mixin.py:188} INFO - [2024-06-19T20:41:50.789+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/fill_data.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/fill_data.py", line 41
    del equipos_actuales(random_equipo)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: cannot delete function call
[2024-06-19T20:41:50.791+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/fill_data.py
[2024-06-19T20:41:50.804+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/fill_data.py took 0.031 seconds
[2024-06-19T20:42:21.490+0000] {processor.py:161} INFO - Started process (PID=343) to work on /opt/airflow/dags/fill_data.py
[2024-06-19T20:42:21.492+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/fill_data.py for tasks to queue
[2024-06-19T20:42:21.494+0000] {logging_mixin.py:188} INFO - [2024-06-19T20:42:21.494+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/fill_data.py
[2024-06-19T20:42:21.501+0000] {logging_mixin.py:188} INFO - [2024-06-19T20:42:21.500+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/fill_data.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/fill_data.py", line 41
    del equipos_actuales(random_equipo)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: cannot delete function call
[2024-06-19T20:42:21.502+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/fill_data.py
[2024-06-19T20:42:21.517+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/fill_data.py took 0.033 seconds
[2024-06-19T20:42:51.839+0000] {processor.py:161} INFO - Started process (PID=350) to work on /opt/airflow/dags/fill_data.py
[2024-06-19T20:42:51.841+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/fill_data.py for tasks to queue
[2024-06-19T20:42:51.844+0000] {logging_mixin.py:188} INFO - [2024-06-19T20:42:51.843+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/fill_data.py
[2024-06-19T20:42:51.851+0000] {logging_mixin.py:188} INFO - [2024-06-19T20:42:51.850+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/fill_data.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/fill_data.py", line 41
    del equipos_actuales(random_equipo)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: cannot delete function call
[2024-06-19T20:42:51.851+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/fill_data.py
[2024-06-19T20:42:51.865+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/fill_data.py took 0.033 seconds
[2024-06-19T20:43:22.252+0000] {processor.py:161} INFO - Started process (PID=357) to work on /opt/airflow/dags/fill_data.py
[2024-06-19T20:43:22.254+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/fill_data.py for tasks to queue
[2024-06-19T20:43:22.257+0000] {logging_mixin.py:188} INFO - [2024-06-19T20:43:22.257+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/fill_data.py
[2024-06-19T20:43:22.264+0000] {logging_mixin.py:188} INFO - [2024-06-19T20:43:22.263+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/fill_data.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/fill_data.py", line 41
    del equipos_actuales(random_equipo)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: cannot delete function call
[2024-06-19T20:43:22.265+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/fill_data.py
[2024-06-19T20:43:22.279+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/fill_data.py took 0.033 seconds
[2024-06-19T20:43:52.507+0000] {processor.py:161} INFO - Started process (PID=364) to work on /opt/airflow/dags/fill_data.py
[2024-06-19T20:43:52.508+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/fill_data.py for tasks to queue
[2024-06-19T20:43:52.512+0000] {logging_mixin.py:188} INFO - [2024-06-19T20:43:52.511+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/fill_data.py
[2024-06-19T20:43:52.517+0000] {logging_mixin.py:188} INFO - [2024-06-19T20:43:52.516+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/fill_data.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/fill_data.py", line 41
    del equipos_actuales(random_equipo)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: cannot delete function call
[2024-06-19T20:43:52.518+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/fill_data.py
[2024-06-19T20:43:52.528+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/fill_data.py took 0.028 seconds
[2024-06-19T20:44:23.037+0000] {processor.py:161} INFO - Started process (PID=371) to work on /opt/airflow/dags/fill_data.py
[2024-06-19T20:44:23.038+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/fill_data.py for tasks to queue
[2024-06-19T20:44:23.040+0000] {logging_mixin.py:188} INFO - [2024-06-19T20:44:23.039+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/fill_data.py
[2024-06-19T20:44:23.045+0000] {logging_mixin.py:188} INFO - [2024-06-19T20:44:23.044+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/fill_data.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/fill_data.py", line 41
    del equipos_actuales(random_equipo)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: cannot delete function call
[2024-06-19T20:44:23.046+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/fill_data.py
[2024-06-19T20:44:23.058+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/fill_data.py took 0.029 seconds
[2024-06-19T20:44:57.474+0000] {processor.py:161} INFO - Started process (PID=378) to work on /opt/airflow/dags/fill_data.py
[2024-06-19T20:44:57.475+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/fill_data.py for tasks to queue
[2024-06-19T20:44:57.477+0000] {logging_mixin.py:188} INFO - [2024-06-19T20:44:57.477+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/fill_data.py
[2024-06-19T20:44:57.483+0000] {logging_mixin.py:188} INFO - [2024-06-19T20:44:57.482+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/fill_data.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/fill_data.py", line 41
    del equipos_actuales(random_equipo)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: cannot delete function call
[2024-06-19T20:44:57.484+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/fill_data.py
[2024-06-19T20:44:57.497+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/fill_data.py took 0.029 seconds
[2024-06-19T20:45:31.457+0000] {processor.py:161} INFO - Started process (PID=385) to work on /opt/airflow/dags/fill_data.py
[2024-06-19T20:45:31.459+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/fill_data.py for tasks to queue
[2024-06-19T20:45:31.461+0000] {logging_mixin.py:188} INFO - [2024-06-19T20:45:31.460+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/fill_data.py
[2024-06-19T20:45:31.466+0000] {logging_mixin.py:188} INFO - [2024-06-19T20:45:31.465+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/fill_data.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/fill_data.py", line 41
    del equipos_actuales(random_equipo)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: cannot delete function call
[2024-06-19T20:45:31.466+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/fill_data.py
[2024-06-19T20:45:31.477+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/fill_data.py took 0.027 seconds
[2024-06-19T20:46:05.542+0000] {processor.py:161} INFO - Started process (PID=392) to work on /opt/airflow/dags/fill_data.py
[2024-06-19T20:46:05.543+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/fill_data.py for tasks to queue
[2024-06-19T20:46:05.544+0000] {logging_mixin.py:188} INFO - [2024-06-19T20:46:05.544+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/fill_data.py
[2024-06-19T20:46:05.548+0000] {logging_mixin.py:188} INFO - [2024-06-19T20:46:05.547+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/fill_data.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/fill_data.py", line 41
    del equipos_actuales(random_equipo)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: cannot delete function call
[2024-06-19T20:46:05.548+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/fill_data.py
[2024-06-19T20:46:05.560+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/fill_data.py took 0.023 seconds
[2024-06-19T20:46:38.709+0000] {processor.py:161} INFO - Started process (PID=399) to work on /opt/airflow/dags/fill_data.py
[2024-06-19T20:46:38.710+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/fill_data.py for tasks to queue
[2024-06-19T20:46:38.712+0000] {logging_mixin.py:188} INFO - [2024-06-19T20:46:38.711+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/fill_data.py
[2024-06-19T20:46:38.717+0000] {logging_mixin.py:188} INFO - [2024-06-19T20:46:38.716+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/fill_data.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/fill_data.py", line 41
    del equipos_actuales(random_equipo)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: cannot delete function call
[2024-06-19T20:46:38.718+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/fill_data.py
[2024-06-19T20:46:38.731+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/fill_data.py took 0.029 seconds
[2024-06-19T20:47:14.183+0000] {processor.py:161} INFO - Started process (PID=406) to work on /opt/airflow/dags/fill_data.py
[2024-06-19T20:47:14.184+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/fill_data.py for tasks to queue
[2024-06-19T20:47:14.186+0000] {logging_mixin.py:188} INFO - [2024-06-19T20:47:14.185+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/fill_data.py
[2024-06-19T20:47:14.190+0000] {logging_mixin.py:188} INFO - [2024-06-19T20:47:14.189+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/fill_data.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/fill_data.py", line 41
    del equipos_actuales(random_equipo)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: cannot delete function call
[2024-06-19T20:47:14.190+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/fill_data.py
[2024-06-19T20:47:14.200+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/fill_data.py took 0.021 seconds
